spring.application.name=SkillInsem

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/fsadexam
spring.datasource.username=root
spring.datasource.password=Mahesh@3164

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Server Port
server.port=8080
